# Build script
build_script:
  - ps: .\build.ps1

version: '{build}'
# Tests
test: off

environment:
  myget_key:
    secure: RMt+ThGgrTCbyy4LE/1rd+i1tT815ahgCMMjzXyLs6f/SvW8XGKRts2agrVXovYD
  nuget_key:
    secure: j8FJm6D/lMnLTBJeRwa08RNDi1cZs+junq4tZsN4vDGTtkmncomdltTbhB86IpoD
