image: Visual Studio 2019
configuration: Release
branches:
  only:
    - master

# build config
build_script:
  - dotnet build .\src

# tests config
test_script:
  - dotnet test .\src

# pack config
after_test:
  - dotnet pack .\src

# artifacts config
artifacts:
  - path: '.\build\artifacts\*.nupkg'

deploy: off

for:
-
  branches:
    only:
       - master

  deploy:
    - provider: NuGet
      api_key:
        secure: GkmEdaMfjFIaqYGW8+58yA8DAprXCBkKgWwAhrDEf+je0agDSJu+HTGnirIypBeC

-
  branches:
    only:
      - dev

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/codestellation/api/v2/package
      api_key:
        secure: sJ2aZzbtBoHsDlBJ7A7D62AVhDtXKZqWt30LWICqgpzALm0bEIGl96SfLg+Uoa3o